### ISSUE TITLE
Adding pagination

### ISSUE THREAD

**Issue by digitalcraftsman** [gohugoio/hugoThemesSite#13]
It's just an idea but I think it would be senseful to add a pagination to the `index.html` since the list of themes is already quite large and will grow in the future. Therefore a user needs, who browses the theme, has just a huge list.

Furthermore would this increase performance, since less items need to loaded and rendered.

**Comment by dplesca** [comment]
I'm not sure I see the point of pagination in this case. I would like to see all the available themes without clicking through several pages, maybe we should emphasize the tags somehow, for better filtering of themes.

Performance-wise we can make the theme thumbnails to be lazy-loaded so that no excessive downloading takes place. The extra html impact should be pretty marginal.

**Comment by digitalcraftsman** [comment]
That would be a good compromise. I created already an issue #10 for the filtering.

**Comment by bep** [comment]
Let us close this for now.
