### ISSUE TITLE
http://themes.gohugo.io/ site is not serving

### ISSUE THREAD

**Issue by kotp** [gohugoio/hugoThemesSite#5]
The site is down, or incorrect, in either case, it is not available when I try to browse there from the [repository](https://github.com/spf13/hugoThemesSite) link at the top.

**Comment by bep** [comment]
It's under construction and not live, yet.

**Comment by kotp** [comment]
This issue is now closed, so indicating that it is now live?  Or the dead link is gone, or a notification that it is not yet live is communicated where it is posted?  Or am I reading too much into the communciation that a closed issue provides?

**Comment by bep** [comment]
I would say it's fair to say that it's a bug/issue if Google.com is down.

A site that is under construction: I would say that this is the normal situation, and closing the issue seems fair.

Having issues for everything that isn't -- isn't worth it.

But, feel free to disagree.

I will add a note in the README that it isn't up yet.

**Comment by kotp** [comment]
Yeah, the only thing I was commenting on was the 'close' without a comment as to what that communicates itself.  Also, without a label, it was hard to take the intent of the close for what it was.

Thanks for the note in README, at least.  I think a one word addition to "Site Layout for http://themes.gohugo.io . Includes script to generate content from all themes in hugoThemes." with the word "Future" prepended would be sufficient.

It is the very first thing we see on the second line when we open up [repository](https://github.com/spf13/hugoThemesSite).
