### ISSUE TITLE
Losslessly optimize all images on site

### ISSUE THREAD

**Issue by coliff** [gohugoio/hugoThemesSite#64]
Huge file-size savings can be had if all the images in this repo are losslessly optimized. I suggest to install either:

- **ImgBot** - a free (for open-source projects) GitHub app https://github.com/marketplace/imgbot

- **Calibre Image-Actions** - a new free GitHub Action which works in a similar way https://github.com/marketplace/actions/image-actions

**Comment by bep** [comment]
I assume you mean all the different thumbnails. These are spread out into all of the 300+ themes repos, so something like a GH action would not work. I have some plans to rewrite the script (to use Hugo Modules), but time ...

**Comment by coliff** [comment]
ah ok - maybe consider using either of those GitHub Apps/Actions on the Docs sites? I have a fork of that and ImgBot ran against it and reduced image-sizes by average 13% across 169 images. If you'd prefer me to make a PR of that I can but ImgBot is a better long-term solution as it can work against future PRs

**Comment by bep** [comment]
GitHub actions are on my "todo list". Are you sure image-actions don't work on future PRs?

**Comment by coliff** [comment]
Great! sorry if my previous message wasn't too clear. I meant that me making a PR right now won't take care of future PRs. Yes, the image-actions does work against all future PRs. I've been testing this today as it happens.

**Comment by bep** [comment]
See https://github.com/gohugoio/hugoDocs/pull/915

**Comment by onedrawingperday** [comment]
I had a look at this issue and as pointed out above theme screenshots are provided from the repos of the different themes.

GitHub Actions do not apply in this case.

One approach would be to modify the [Build Script](https://github.com/gohugoio/hugoThemes/blob/master/_script/generateThemeSite.sh) to call ImageMagick* so that the original images are compressed right before the `hugo` command.

But then again on the deployed website all images are already processed through Hugo's Image Processing.

So I cannot see why we would need to do the above. It will not change anything in the User Experience since the images on the ThemesSite are supposed to be already optimized.

---

*ImageMagick [is available](https://github.com/netlify/build-image/blob/trusty/included_software.md) in the Netlify Build Image that is currently used by the ThemesSite.
