### ISSUE TITLE
{{ .Permalink }} makes double slash url

### ISSUE THREAD

**Issue by zzossig** [gohugoio/hugoThemesSite#72]
It happens not only in my project but also in other demo sites.
And this issue makes some "cors" issue on my project exampleSite.
![doubleslash](https://user-images.githubusercontent.com/52706977/70490209-2a9d5680-1b41-11ea-8a2a-784ece6c6991.png)

**Comment by onedrawingperday** [comment]
This support question belongs to the [Hugo Discussion Forum](https://discourse.gohugo.io/). 

The GitHub issues of this repo are only for theme submissions or problems relating to the Themes Site.

Thank you.

**Comment by onedrawingperday** [comment]
You are not using `.Permalink` but `.RelPermalink`  to generate a sub list.

As you know the theme demo is hosted in a subdirectory. There is a double slash due to the use of `.RelPermalink` over [here](https://github.com/zzossig/hugo-theme-zzo/blob/d182e8f15ad0d44562ceb65d00ae030d92bd419a/layouts/partials/sidebar/sidebar-list.html#L12)

**Comment by zzossig** [comment]
But, I use .Permalink as well. [Here](https://github.com/zzossig/hugo-theme-zzo/blob/6e1ff92a2d4e8674d40cc914d2128b891425ed8d/layouts/partials/summary/classic.html#L13)
I have other links that using .Permalink that makes double slashes.

**Comment by onedrawingperday** [comment]
Right. The demo configuration is still inherited from the provided config.

There is a back slash at the end of the baseURL in the [`exampleSite/config/_default/config.toml`](https://github.com/zzossig/hugo-theme-zzo/blob/6e1ff92a2d4e8674d40cc914d2128b891425ed8d/exampleSite/config/_default/config.toml#L1)

Try removing this back slash and let me know so that I can see if that fixes the issue.

**Comment by zzossig** [comment]
I can't reproduce the double slashes issue on my end.
Test env: macOS High Sierra 10.13.6/ Hugo 0.60.1
I have tested 4 times:
```
baseURL = "" 
```
```
baseURL = "/" 
```
```
baseURL = "http://example.org" 
```
```
baseURL = "http://example.org/"
```
It seems that baseURL is not impacted the url.
<img width="1280" alt="Screen Shot 2019-12-10 at 9 09 35 PM" src="https://user-images.githubusercontent.com/52706977/70528475-a0c9a980-1b91-11ea-89ff-2a13b0ec89a2.png">

**Comment by onedrawingperday** [comment]
Please do as I requested above and let me know, my time is limited.

**Comment by zzossig** [comment]
I don't understand. I did what you requested

**Comment by zzossig** [comment]
As you can see [here](https://github.com/thingsym/hugo-theme-techdoc/blob/d6d3a9370b4a89a6e5c81f4a5778f940b11daa14/exampleSite/config.toml#L1)
techdoc theme does not have the end of backslash but the theme also have a double backslash issue.

tell me what I'm doing wrong.

**Comment by onedrawingperday** [comment]
>I don't understand. I did what you requested

How? 

You still haven't removed the backslash from the exampleSite config as I requested above.

And commit it to the zzo theme repo.  (Obviously).

I need to trigger a proper deploy preview of the Hugo Themes website.

Also please keep communication to a minimum. You asked about your theme demo.

I cannot explain the architecture of Hugo Themes on demand. 
There are more important things to do than writing long-form.

**Comment by zzossig** [comment]
@onedrawingperday sorry,
I just commited

**Comment by onedrawingperday** [comment]
After much investigation it seems like this is related to this longstanding and open bug:

https://github.com/gohugoio/hugo/issues/3568

~~I'm closing this issue since it depends on the one I linked to, at the main Hugo repo.~~

But I'm not sure. I have re-opened the issue.

Maybe someone else has the time to look into it.

**Comment by zzossig** [comment]
I'm so sorry for taking too much time. I should have searched for it
